- name: playlevel & task level variables
  hosts: local
  connection: local
  vars:
   Name: "rajureddy"
   dob: 26 April-2026
   Address: Karimnagar

  tasks:
    - name: this is one of task in my playbook
      vars:
       Address: warangal
      ansible.builtin.debug: 
       msg: "{{Name }} born on {{dob}} in {{Address}}"  