- name: accessing variables from other yaml file
  hosts: local
  connection: local
  vars_files:
  - myvariables.yaml
  tasks:
   - name: printing those variables
     vars:
      Skillset: Java 
     ansible.builtin.debug: 
      msg: " {{Name}} born in {{Birthplace}} having Skill in {{Skillset}} "
