- name: shell module
  hosts: local
  connection: local

  tasks:
  - name: shell module
    #ansible.builtin.shell: echo $HOME 
    #ansible.builtin.shell: echo $USER 
    ansible.builtin.shell: echo $PATH 
    register: output

  - name: print
    ansible.builtin.debug: 
     msg: "{{output.stdout}}  "