- name: converting dictionary into list using filters
  hosts: local
  connection: local
  
  vars:
   tagsmap: # dictonary/map/Hash
    Name: ansible
    Project: Roboshop
    Component: Catalogue
    myIp: 255.233.34.10

   tagslist: [  # list of maps
    {'key': 'Name', 'value': 'ansible'},
     {'key': 'Project', 'value': 'Roboshop'},
      {'key': 'Component', 'value': 'Catalogue'}
    ]
 
  tasks:
   - name: convert dictionary to list
     ansible.builtin.debug:
      msg: " List of {{ tagsmap | dict2items }}"   
  
   - name: convert list to dict 
     ansible.builtin.debug:
      msg: " {{ tagslist | items2dict}}"  

   - name: convert to upper case
     ansible.builtin.debug:
      msg: "{{Name | upper }}"

   - name: convert to lower case
     ansible.builtin.debug:
      msg: "{{Name | lower }}"

   - name: read yamlfile 
     ansible.builtin.set_fact: # setting up variable "  employee_data " & storing the yaml file in it ,in future i can use this variable
      employee_data: " {{ lookup('file', 'Employeedata.yaml') | from_yaml}}"

   - name: convert to json
     ansible.builtin.debug:
      msg: "{{employee_data|to_json}}"

   - name: check given IP is IPV4 or not
     ansible.builtin.debug:
      msg: "{{ myIp | default('0.0.0.0') | ansible.utils.ipv4 }}"
   