- name: converting dictionary into list using filters
  hosts: local
  connection: local
  
  vars:
   tagsmap: # dictonary/map/Hash
    Name: ansible
    Project: Roboshop
    Component: Catalogue

   tagslist: [  # list of maps
    {'key': 'Name', 'value': 'ansible'},
     {'key': 'Project', 'value': 'Roboshop'},
      {'key': 'Component', 'value': 'Catalogue'}
    ]
 
  tasks:
   - name: convert dictionary to list
     ansible.builtin.debug:
      msg: " List of {{ tagsmap | dict2items }}"   
  
   - name: convert list to dict 
     ansible.builtin.debug:
      msg: " {{ tagslist | items2dict}}"  

   - name: convert to upper case
     ansible.builtin.debug:
      msg: " course | upper "
   